[package]
name = "rust_experiments"
version = "0.1.0"
authors = ["Julius G-B"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"